### ISSUE TITLE
Patch on boolean attributes fails

### ISSUE THREAD

**Issue by psvo** [Captain-P-Goldfish/SCIM-SDK#105]
When patching a boolean attribute, for example `User:active`, the request fails due to PatchOp validation. For example:

```
PATCH /Users/id
Content-Type: application/scim+json

{
  "Operations": [
    {
      "op": "replace",
      "path": "active",
      "value": true
    }
  ],
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:PatchOp"
  ]
}
```
Fails with:
```
{
  "detail": "value of field with name 'urn:ietf:params:scim:api:messages:2.0:PatchOp:Operations.value' is not of type 'string' but of type: boolean",
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:Error"
  ],
  "status": 400
}
```

The PathOp declares the value attribute as string/multivalue. On the other hand, a json object in the value is (incorrectly?) accepted due the this check:

```java
// class SchemaValidator
//   private JsonNode validateComplexAndArrayTypeAttribute(JsonNode document, SchemaAttribute schemaAttribute)
      if (isSimpleMultiValuedExpected && !isNodeSimpleMultiValued && !isNodeMultiValuedComplex)
      {
        ArrayNode arrayNode = new ScimArrayNode(schemaAttribute);
        arrayNode.add(document);
        return arrayNode;
      }
```

It seems for PatchOp value validation, the SCIM type system is not sufficient and some custom extension will be needed, because the value can have any type. Surprisingly, the following request succeeds, although the active has type boolean:

```
PATCH /Users/id
Content-Type: application/scim+json

{
  "Operations": [
    {
      "op": "replace",
      "path": "active",
      "value": "true"
    }
  ],
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:PatchOp"
  ]
}
```

**Comment by Captain-P-Goldfish** [comment]
I just added a new commit that fixes this problem.
I added a new type-attribute that is not defined by SCIM. The type-attribute of an attribute-declaration can now get the value "any". This will internally resolve the value into a string representation during patch-op validation but will then be correctly parsed during document schema validation.
Since the Jackson TextNode is also providing methods for directly parsing the current value to any specific type this fix should hopefully do.
Check it out :-)
