### ISSUE TITLE
Expose attributes and excludedAttributes in ResourceHandler#getResource

### ISSUE THREAD

**Issue by psvo** [Captain-P-Goldfish/SCIM-SDK#107]
Would consider pull-request exposing supplied attributes and excludedAttributes to the ResourceHandler#getResource API call?

It would allow avoiding possibly expensive joins when retrieving the data from storage (e.g. large set of group members) in a similar way how listResources currently works.

I'm thinking about the following change in the ResourceHandler API:

```java
// class ResourceHandler<T>

public T getResource(String id, Authorization auth) {
   // don't want it abstract, because then you would have to implement both getResource methods
   throw NotImplementedException(...); // or InternalServerError?
}

public T getResource(String id, List<SchemaAttribute> attributes, List<SchemaAttribute> excludedAttributes, Authorization auth) {
   return getResource(id, auth);
}
```

Call the  `getResource(String, List<SchemaAttribute>, List<SchemaAttribute>, Authorization)` from the `ResourceEndpointHandler#getResource(String, String, String, String, Map<String,String>, Supplier<String>, Authorization)`

It seems it would be helpful to move attribute parsing outside of the SchemaValidator, because in case of the list request, it's done by the endpoint list method and then again by the SchemaValidator constructor. But that's just an optimization, that's not really required for this change.

What do you think? Thanks!

**Comment by Captain-P-Goldfish** [comment]
That's actually the second time I was asked to do this exactly for the mentioned reason to avoid expensive joins :-)
I will extend the getResource method by these parameters for 1.9.0.

**Comment by Captain-P-Goldfish** [comment]
just to be clear:
you mentioned a pull request. Do you want to do it or do you prefer me to do this? :-) I am not standing in your way if you want to extend this feature.

**Comment by psvo** [comment]
You said: `I will extend the getResource method by these parameters for 1.9.0.` so I have stayed tuned. ;)

I should be able to prepare a PR for this probably sometime this week. Do you want the API exactly as I have displayed or would you prefer some changes?

BTW I found, that the PATCH should also support the attributes query parameter. But PUT does not. So, I'm not sure how this could be exposed in the API, because PATCH is implemented as GET-modify-PUT. I haven't looked into that.

**Comment by Captain-P-Goldfish** [comment]
It's okay. I just wanted to know if you insist. I am already at it :-)

If patch would support these parameters then it would also make sense to add those to create and update. But this is not defined in RFC7644 but it might be useful for services that store large resources.

The result would be:
POST: supports attributes but the attributes are not handed over to the handler since these attributes can be handled on API level.
PUT: is not passing the parameters to the handler since put is considered as a whole replacement. So the attributes would be handled on API level for response
PATCH: does not pass the attributes to the get-call to retrieve the full resource does then patch the resource and calls the update method to execute a full replacement. Eventually the parameters are again handled on API level.

So these methods will not receive these parameters. But I might add them as supported attributes to reduce the number of returned attributes after create, update or patch.

**Comment by psvo** [comment]
> It's okay. I just wanted to know if you insist. I am already at it :-)

:+1: I don't insist. :)

> If patch would support these parameters then it would also make sense to add those to create and update. But this is not defined in RFC7644 but it might be useful for services that store large resources.

For PATCH, the "attributes" param is defined in the RFC 7644 (and SCIM-SDK seems to support it already):

> On successful completion, the server either MUST return a 200 OK response code and the entire resource within the response body, subject to the **"attributes"** query parameter (see Section 3.9), or MAY return HTTP status code 204 (No Content) and the appropriate response headers for a successful PATCH request.  The server MUST return a 200 OK if the "attributes" parameter is specified in the request.

For performance reasons it could be even useful to support the 204 response on PATCH too.

I agree that for the rest of the methods (POST/PUT) none are defined.

**Comment by Captain-P-Goldfish** [comment]
I just checked, attributes and excludedAttributes are already evaluated in patch requests.
But I will not pass these attributes to the getResource method because patch expects to get the whole resource that is then patched and eventually passed to the updateResource method that is expected to do a complete resource update to keep the logic simple. This is indeed an impact in performance But I don't see a reliable way to solve this in any other way in its current state.
