### ISSUE TITLE
Empty result when pagesize (count) is smaller than startIndex

### ISSUE THREAD

**Issue by HoaiDang-work** [Captain-P-Goldfish/SCIM-SDK#131]
My List User request: <domain>/scim/v2/Users?startIndex=11&count=10&filter=externalId pr
I have more than 100 users, want to get 10 users started from index 11, I got empty response.

**Comment by Captain-P-Goldfish** [comment]
How many results are returned if you remove "startIndex" and "count"?
This is actually intentional behaiour. Filtering is executed before stripping left and right results. So if your query does return less than 10 users you obiously get an empty result since the startIndex is out of range.
I just ran some tests with this and I could not find any actual issues. You are free to prove me wrong but I would need more information to find the cause since I am not able to reproduce this.

**Comment by HoaiDang-work** [comment]
FYI...I don't use auto filterting. If i remove startIndex and count and call this request scim/v2/Users?filter=externalId pr, the result is as I expected:  
  "totalResults": 192,
  "itemsPerPage": 50,
  "startIndex": 1,

The "Resources" list has 50 items.

**Comment by Captain-P-Goldfish** [comment]
I see this is indeed a big problem. I will try to fix it until evening.

**Comment by Captain-P-Goldfish** [comment]
I worked out a solution. If you have a better idea please bring it out:

my idea:
I added a new field to class `de.captaingoldfish.scim.sdk.server.response.PartialListResponse` with name `startIndexUsed`. If this field is set to true the startIndex will no longer be evaluated by the scim api. This would also be backwards compatible. But you would have to set this value to true if you do this directly on database-level.

**Comment by HoaiDang-work** [comment]
How about you just do the checking when auto-filtering is true? If the app implements the pagination on its own, it is responsible to retrieve the correct result.
