### ISSUE TITLE
No authentication checking when authenticated is true but Authorization object is not present

### ISSUE THREAD

**Issue by HoaiDang-work** [Captain-P-Goldfish/SCIM-SDK#132]
With the below code snippet, I can go straight to the endpoints without providing any Authorization.

private void authenticateClient(UriInfos uriInfos, Authorization authorization)
  {
    ResourceType resourceType = uriInfos.getResourceType();
    if (!resourceType.getFeatures().getAuthorization().isAuthenticated())
    {
      // no authentication required for this endpoint
      return;
    }
    Optional.ofNullable(authorization).ifPresent(auth -> {
      boolean isAuthenticated = auth.authenticate(uriInfos.getHttpHeaders(), uriInfos.getQueryParameters());
      if (!isAuthenticated)
      {
        log.error("authentication has failed");
        throw new UnauthenticatedException("not authenticated", getServiceProvider().getAuthenticationSchemes(),
                                           auth.getRealm());
      }
    });
  }

**Comment by Captain-P-Goldfish** [comment]
This is actually an intentional implementation detail. 
If the developer wishes to use the authentication and authorization extension an implementation of the `Authorization`-interface must be provided. But if the interface implementation is missing the feature is expected to be disabled. There might be some simplified cases in which only authentication is required but not authorization. In such cases it is unnecessary to use this feature since the authentication will probably be executed on another implementation layer.

But I have to agree this is not mentioned in the documentation. I keep the ticket open until I added this information to the documentation.

**Comment by Captain-P-Goldfish** [comment]
I added a log-warning in case that authentication is required but deactivated. I think this is the best thing to do here since its an implementation detail. I also updated the documentation: https://github.com/Captain-P-Goldfish/SCIM-SDK/wiki/Authentication-and-Authorization
