### ISSUE TITLE
[Feature Discussion] Async

### ISSUE THREAD

**Issue by petersondrew** [Captain-P-Goldfish/SCIM-SDK#263]
Would you be open to an async version of the ResourceEndpoint and handler callbacks? I'd be willing to put in the work and open a PR but wanted to have a discussion before I did any work.

Thanks!

**Comment by Captain-P-Goldfish** [comment]
I am not sure if I can follow you here. From my point of view the ResourceEndpoint is capable of accepting multiple requests simultanously without getting any concurrency issues so I am not sure what you mean with `async version`.
But I am always open for great extensions that make life easier :-)

**Comment by petersondrew** [comment]
First, I want to make a correction, everywhere I've mentioned `Future` I actually mean `CompletableFuture`. 😄 

Second, it is possible to do what you're proposing, it just becomes even more cumbersome in our case where we use database libraries that return `CompletableFuture` inside the `User` resource handler. So it becomes necessary for us to also wait for completion in the handler because of third party code returning `CompletableFuture`, as well as in our controller to avoid blocking threads that are handling incoming requests. 

If it's a matter of the work required, I'm more than happy to do it, but obviously I don't want to work on something that you're not comfortable with.

**Comment by Captain-P-Goldfish** [comment]
I see your current problem and I am open for discussion but I think adding additional methods will not solve your current problem. Did you already see the code of the class `ResourceEndpointHandler`?
Lets go through your scenario in case of list-resources:
1. request comes in and enters successfully the `listResource`-method within the `ResourceEndpointHandler`
2. the request data is being validated, the `ResourceType` is determined and your `ResourceHandler`-implementation is called

Now we come to the problematic point and please correct me if you see that I am wrong.

3. you execute heavy statements within your database that will e.g. take up to 10 seconds (just a random value now)
4. You receive a `CompletableFuture` from your driver and you want to return it.

Now it gets funny

5. the `CompletableFuture` is returned to the `ResourceHandlerEndpoint`.
6. The `ResourceHandlerEndpoint` does now expect to receive the results from the `ResourceHandler` (`CompletableFuture` which itself is also a `Future` as we know) and tries to validate the returned results.
7. In order to be able to validate the results the `ResourceHandlerEndpoint` needs the returned results from your database. So its is necessary that the result from your `Future` is already present in order for the `ResourceHandlerEndpoint` to do its work (schema validation and checking that the correct amount of results are returned etc.).

So in order to change this there would be some more adjustments necessary than just adding a few methods. From this side I am currently not convinced that this might be the right solution.
But I am always open for critical reviews on my opinion :-)

**Comment by petersondrew** [comment]
That makes sense, yes I hadn't look deeply enough into the codebase to see how far down we'd need to go with Future support. When I have some spare cycles I might take a stab at it and see how big of a change it would be so we have something concrete to look at and discuss - for now though I think we'll just wrap the call to `handleRequest` in a Future so we don't block our threadpool threads answering requests.

**Comment by Captain-P-Goldfish** [comment]
Sounds like a plan :-)
I hope adding an additional call around this does not cause too much of a problem. I am closing this issue for now but feel free to reopen if something else comes to mind :-)
