### ISSUE TITLE
Add canonicalValues sub attribute in emails

### ISSUE THREAD

**Issue by abeysith** [Captain-P-Goldfish/SCIM-SDK#319]
I was trying to integrate scim server with Sailpoint and found that "emails" field is not recognized, and it was due to "cannonicalValues" subattribute is not defined in the schema. Is it possible to add this sub attribute to default User schema so that we don't need to overwrite default schema.
existing email sub attributes 
     {

            "name": "type",

            "type": "string",

            "multiValued": false,

            "description": "A label indicating the attribute's function, e.g., 'work' or 'home'.",

            "required": false,

            "caseExact": false,

            "mutability": "readWrite",

            "returned": "default",

            "uniqueness": "none"
           
        }

new sub attributes
"canonicalValues": [

                                "work",

                                "home",

                                "other"

                            ],
Ref [RFC] (https://datatracker.ietf.org/doc/html/rfc7643#section-2.4)

**Comment by Captain-P-Goldfish** [comment]
Hi, unfortunately that is not possible. I know at least 3 applications that are not under my control that would break with this change because they use also other values. 
Also the type value is actually misused in the server-implementation. You can use it to enter the name of a resource-type and the server-implementation will use it to automatically enter the correct $ref-attribute address.

If you do not want to copy and modify the complete schema and reregister the endpoint you could still override the schema during runtime. It does not contain any setter-methods to do so but the `Schema` class is simply an extension of the jackson `ObjectNode` so you can still do something like this:

```java
    ResourceType userResourceType = resourceEndpoint.registerEndpoint(new UserEndpointDefinition(new UserHandler()));
    Schema schema = userResourceType.getMainSchema();
    SchemaAttribute schemaAttribute = schema.getSchemaAttribute("emails.type");
    ArrayNode canonicalValues = new ArrayNode(JsonNodeFactory.instance);
    canonicalValues.add("work");
    canonicalValues.add("home");
    canonicalValues.add("other");
    schemaAttribute.set(AttributeNames.RFC7643.CANONICAL_VALUES, canonicalValues);
```

This little trick can be used to modify the configuration during runtime
