### ISSUE TITLE
PatchOp Replace 

### ISSUE THREAD

**Issue by abeysith** [Captain-P-Goldfish/SCIM-SDK#327]
We are integrating the scim server with Sailpoint and  sailpoint trigger following patch Operation.
```
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:PatchOp"
    ],
    "Operations": [
        {
            "op": "replace",
            "value": {
                "name": {
                    "familyName": "testFamily"
                }
            }
        },
        {
            "op": "replace",
            "value": {
                "name": {
                    "givenName": "testGivenName"
                }
            }
        }
    ]
}
```
 I found that the whole name.givenName is set as "testGivenName". and name.familyName: null
 but expectation is name.givenName= "testGivenName"
name.familyName="testFamily"

According to RFC it should follows the rule
If the target location specifies a complex attribute, a set of
      sub-attributes SHALL be specified in the "value" parameter, which
      replaces any existing values or adds where an attribute did not
      previously exist.  Sub-attributes that are not specified in the
      "value" parameter are left unchanged.

Is this a known issue?.Will there be a fix or any workaround
[3.5.2.3](https://datatracker.ietf.org/doc/html/rfc7644#section-3.5.2.3).  
Replace Operation

   The "replace" operation replaces the value at the target location
   specified by the "path".  The operation performs the following
   functions, depending on the target location specified by "path":

   o  If the "path" parameter is omitted, the target is assumed to be
      the resource itself.  In this case, the "value" attribute SHALL
      contain a list of one or more attributes that are to be replaced.

   o  If the target location is a single-value attribute, the attributes
      value is replaced.

   o  If the target location is a multi-valued attribute and no filter
      is specified, the attribute and all values are replaced.

   o  If the target location path specifies an attribute that does not
      exist, the service provider SHALL treat the operation as an "add".

   **o  If the target location specifies a complex attribute, a set of
      sub-attributes SHALL be specified in the "value" parameter, which
      replaces any existing values or adds where an attribute did not
      previously exist.  Sub-attributes that are not specified in the
      "value" parameter are left unchanged.**

   o  If the target location is a multi-valued attribute and a value
      selection ("valuePath") filter is specified that matches one or
      more values of the multi-valued attribute, then all matching
      record values SHALL be replaced.

   o  If the target location is a complex multi-valued attribute with a
      value selection filter ("valuePath") and a specific sub-attribute
      (e.g., "addresses[type eq "work"].streetAddress"), the matching
      sub-attribute of all matching records is replaced.

   o  If the target location is a multi-valued attribute for which a
      value selection filter ("valuePath") has been supplied and no
      record match was made, the service provider SHALL indicate failure
      by returning HTTP status code 400 and a "scimType" error code of
      "noTarget".

**Comment by Captain-P-Goldfish** [comment]
I could verify this behaviour. This will be fixed within the next release.

**Comment by Captain-P-Goldfish** [comment]
I need to change what I said. Is just investigated some more and noticed whats the problem.

You use two operations that use the replace operation. The value attribute is supposed to be the resource itself so the API will assume that you want to replace the complete name attribute. In order to fix this you will have to use the "add"-op on the second patch operation:

```json
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:PatchOp"
    ],
    "Operations": [
        {
            "op": "replace",
            "value": {
                "name": {
                    "familyName": "testFamily"
                }
            }
        },
        {
            "op": "add",
            "value": {
                "name": {
                    "givenName": "testGivenName"
                }
            }
        }
    ]
}
```

Like this you would get the expected result

**Comment by abeysith** [comment]
my expectation 
from first replace operation replace familyName and keep other sub attributes unchanged
        second replace operation replace the givenName and keep the other sub attributes. (here is a catch here, from the first operation we have change the "familyName" to "testFamily" for the second patch operation have some intermediate updates . and seems library discards it.

**Comment by Captain-P-Goldfish** [comment]
I understand why this is your expectation but the RFC does not clearly specify it this way. If the value is represented by the resource and a complex type is added to it the replace op will replace the complete complex type. Simply use the add op in order to prevent replacing the complete complex type. The add operation behaves the same as the replace op with the difference that not the whole complex type is replaced. Only the given attributes will be added to the complex type and if they already do exist the value is replaced. 

```
[3.5.2.1](https://www.rfc-editor.org/rfc/rfc7644.html#section-3.5.2.1).  Add Operation

...
 o  If the target location exists, the value is replaced.
...
```

Since the SCIM RFC leaves room for interpretation with patch operations I have created this page in order to describe how the behaviour was implemented:
https://github.com/Captain-P-Goldfish/SCIM-SDK/wiki/Patching-resources

**Comment by abeysith** [comment]
Thanks for the explanation. Unfortunately we don't have control with Sailpoint request.

**Comment by Captain-P-Goldfish** [comment]
I have to admit that I have no idea what the best course of action would be here because a change might break another implementation...

**Comment by Captain-P-Goldfish** [comment]
I thought of a solution.
I will add a new configuration property to the patchConfig that is by default set to false
`handleReplaceAsAddInComplexResourcePatch`
long method name but I cannot think of a better one.
With this property I will change the replace-operation behaviour of complex-attributes to the same as add-operations. But this will be done for single complex types only. Since a multivalued complex is a complete another deal It will be left out from this. 

Would this be sufficient for your usecase?

**Comment by abeysith** [comment]
Yes I think that will work for us. We have trouble with `name`
Thanks you very much for your inputs.

**Comment by Captain-P-Goldfish** [comment]
please check if the workaround works to your liking:

use
```java
serviceProvider.getPatchConfig().setActivateSailsPointWorkaround(true);
```

**Comment by abeysith** [comment]
> please check if the workaround works to your liking:
> 
> use
> 
> ```java
> serviceProvider.getPatchConfig().setActivateSailsPointWorkaround(true);
> ```

Many thanks. Will test this and update you.

**Comment by abeysith** [comment]
are you able to release this change.
