### ISSUE TITLE
logging dependencies

### ISSUE THREAD

**Issue by clarklamgevin** [Captain-P-Goldfish/SCIM-SDK#428]
I am new to using your SCIM server and am loving it. Thank you very much. However, I have noticed that it kills the rest of my service's logging because of apparent dependency on slf4j 2.0. Is there a configuration of some sort to set logging to 1.7.x? I get a warning on the console indicating that "No SLF4J Provider found. Defaulting to NOP logger implementation"

**Comment by Captain-P-Goldfish** [comment]
The problem here is probably the slf4j-api in version 2.0.0.
If you are using log4j2 simply upgrade:
```xml
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-slf4j-impl</artifactId>
                <version>${version.log4j2}</version>
            </dependency>
```
to 
```xml
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-slf4j2-impl</artifactId>
                <version>${version.log4j2}</version>
            </dependency>
```

that should do the trick.

Alternatively try to exclude the slf4j-api from the SCIM-SDK or downgrade the slf4j-api by using the `dependencyManagement` section


If that's not the problem, I would need some more infos.


Glad that the API meets your expectation :-)

**Comment by clarklamgevin** [comment]
Thank you for your response and help.I  downgraded the slf4j-api and that did the trick
