### ISSUE TITLE
Schema for displayName and Patch Operation

### ISSUE THREAD

**Issue by csbrogi** [Captain-P-Goldfish/SCIM-SDK#47]
When I try to patch an user with the request
```
PATCH /auth/realms/REALM/scim/v2/Users/03146c7f-acab-4edd-a6b2-0648ad405eb9
 {
     "schemas":
       ["urn:ietf:params:scim:api:messages:2.0:PatchOp"],
     "Operations": [{
       "op":"replace",
       "path": "displayName",
       "value":     "Erna Elvira Ente"      		
     }]
}
```

I get the error 
```
{
    "detail": "the attribute 'Operations.value' does not apply to its defined type. The received document node is of type 'STRING' but the schema defintion is as follows: \n\tmultivalued: true\n\ttype: STRING\nfor schema with id urn:ietf:params:scim:api:messages:2.0:PatchOp\n\"Erna Elvira Ente\"",
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:Error"
    ],
    "status": 400
}

```
whereas
`       "value":     ["Erna Elvira Ente"]      		`

works, but as far as I understand from rfc7643 *displayName* is a *Singular Attribute*.

**Comment by Captain-P-Goldfish** [comment]
Issue will be resolved with the next release. The solution is a new feature that allows to put single-valued attributes into places where simple multi-valued attributes are expected e.g.:

"numbers": 5

instead of

"numbers": [5]

both variation are valid now. The first variation is detected and automatically wrapped into an array during schema validation
