### ISSUE TITLE
Authentication should be enabled by default in keycloak example

### ISSUE THREAD

**Issue by csbrogi** [Captain-P-Goldfish/SCIM-SDK#5]
We want to use the keycloak example in a production environment. Therefore we want to use a released version of scim-sdk without the need of patching and building it.
Enabling it by system property should be ok.

**Comment by Captain-P-Goldfish** [comment]
I would strongly advise to not use the example in a production environment for the following reasons.

1. authentication is considered in the example but
   - any created client will be able to access the scim endpoints as it is right now 
      - imagine a client that should only be able to authenticate users. This client may authenticate a user and use the received bearer token to do anything on the scim endpoints. The keycloak developers do know about this problem and published the following article: https://www.keycloak.org/docs/latest/server_admin/#_audience
      - The current example does not check if a client has the roles to access the provided endpoints. This is configurable on the `ResourceType` objects but you must pass the information yourself. You may pass ServiceAccount roles for clients or simply client roles. How you solve this is up to you
2. The current example uses my own filtering-implementation. This should be done on database level. Eventhough my personal experience here is that counting the entries to a matching filter becomes very slow due to the user-attribute table. But this becomes a problem on 5000 users or mores if the users have many attributes. Otherwise this should not be a problem.
3. We got the same problem with sorting. This should also be done directly on dataabase level but is done on api level by my implementation.

The keycloak example is really just an example application that shall prove that it integrates smoothly into keycloak. The rest should be accomplished by your own effort. 
If I would have the time to do this I could also implement it directly and send a pull request to keycloak but unfortunately this is currently way too much work to be handled on my own.

But you are free to use change and do anything you want with that example. But please consider the security issues.
