### ISSUE TITLE
Issue with Keycloak/Users version 11.0.3

### ISSUE THREAD

**Issue by RaffaelGrob** [Captain-P-Goldfish/SCIM-SDK#90]
I'm just having the first trial with SCIM/KC. Not sure whether a misconfiguration leads to this. I just ask ...

Requesting users using this powershell leads to a successful authentication and later a throws "{"detail":"sorry but an internal error has occurred.","schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"status":500,"scimType":"invalidValue"}":

$response = Invoke-RestMethod 'https://kc.domain.ch/auth/realms/beta/scim/v2/Users' -Method 'GET' -Headers $headers -Body $body

On Keycloak I observe this:
ERROR [de.captaingoldfish.scim.sdk.common.response.ErrorResponse] (default task-62) the attribute 'userName' must match the regular expression '[a-z\-_ ]+' but value is 'admin.xy@domain.ch': de.captaingoldfish.scim.sdk.common.exceptions.DocumentValidationException: the attribute 'userName' must match the regular expression '[a-z\-_ ]+' but value is 'admin.xy@domain.ch'

the user admin.xy@domain.ch is the first user in the list of my realm. it's not the user I use to login so I guess SCIM just wanted to send me a userlist and struggled with the first one. Is KC 11.0.3 already stable?

thanks!

**Comment by Captain-P-Goldfish** [comment]
This is actually a misconfiguration caused by me. An old relic I forgot to remove when I tried to forge the old sample project into a production environment. Until now there is no way to fix this by webadmin console. But it is planned to be implemented as soon as I get some more free time.

The problem itself can be found in the class "ScimConfiguration" line 106-108. There I am placing a regular expression as attribute restriction for usernames. And this is exactly what you see in the error message ([a-z-_ ]+). Up to version 1.8.1 usernames are restricted to these patterns.
I am going to build a new release that removes the validation from the username.

**Comment by RaffaelGrob** [comment]
thanks!
